spring:
  application:
    name: BonAppetit

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    username: hristo
    password: BCNTntqY6@ja
    url: jdbc:postgresql://flexpostgres.postgres.database.azure.com:5432/bon_appetit

logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

server:
  port: 8081
